Repository theforeman/puppet-pulpcore, pull requests merged in 2020-11, with the labels that each got.

#136 Use Github Actions instead of Travis
  .github/workflows/acceptance.yml
  .github/workflows/cron.yml
  Gemfile
Labels: Modulesync, Needs testing

#127 Support Pulpcore 3.7
  .github/workflows/acceptance.yml
  .github/workflows/cron.yml
  Gemfile
  README.md
  manifests/repo.pp
Labels: Needs testing

#145 support /pulp/deb proxying
  manifests/plugin/deb.pp
  spec/classes/plugin_deb_spec.rb
Labels: Enhancement, Needs testing

#137 Add ability to control if services are enabled or active
  manifests/init.pp
  manifests/service.pp
  spec/classes/pulpcore_spec.rb
Labels: Enhancement, Needs testing

#146 Release 2.1.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog

#148 Set logoutput to on_failure for pulpcore::admin
  manifests/admin.pp
Labels: Needs testing
