Repository theforeman/puppet-pulpcore, pull requests merged in 2020-07, with the labels that each got.

#100 Refs #30057 - Configure Pulpcore Worker Count
  lib/facter/pulpcore_workers.rb
  manifests/init.pp
  manifests/service.pp
  spec/acceptance/basic_spec.rb
  spec/classes/pulpcore_spec.rb
Labels: Needs testing

#108 Clean up tests and get full coverage
  spec/classes/plugin_certguard_spec.rb
  spec/classes/plugin_container_spec.rb
  spec/classes/plugin_file_spec.rb
  spec/classes/plugin_migration_spec.rb
  spec/classes/plugin_rpm_spec.rb
  spec/classes/pulpcore_spec.rb
Labels: Needs testing

#109 Add the GPL license text
  LICENSE
Labels: Needs testing

#112 Fixes #29895 - add pulp_deb plugin
  manifests/plugin/deb.pp
  spec/acceptance/plugins_spec.rb
  spec/classes/plugin_deb_spec.rb
Labels: Enhancement, Needs testing

#114 Sort plugins in acceptance test
  spec/acceptance/plugins_spec.rb
Labels: skip-changelog

#110 Introduce a curl_command helper
  spec/acceptance/basic_spec.rb
  spec/acceptance/plugins_spec.rb
  spec/support/acceptance/curl_command.rb
Labels: Needs testing
