Repository theforeman/puppet-pulpcore, pull requests merged in 2020-10, with the labels that each got.

#125 Drop pid files and fix working dirs
  manifests/service.pp
  templates/pulpcore-api.service.erb
  templates/pulpcore-content.service.erb
  templates/pulpcore-resource-manager.service.erb
  templates/pulpcore-worker@.service.erb
Labels: Needs testing

#123 Add Pulpcore repository class
  manifests/init.pp
  manifests/repo.pp
  spec/classes/pulpcore_spec.rb
  spec/classes/repo_spec.rb
  spec/setup_acceptance_node.pp
  templates/repo.epp
Labels: Needs testing

#126 Fixes #31018 - Force UTF-8 database encoding
  manifests/database.pp
Labels: Needs testing

#116 Fixes #30465 - Use libexec wrappers for SELinux
  README.md
  templates/pulpcore-api.service.erb
  templates/pulpcore-content.service.erb
  templates/pulpcore-resource-manager.service.erb
  templates/pulpcore-worker@.service.erb
Labels: Backwards incompatible, Needs testing

#129 use absolute paths in unit files
  templates/pulpcore-api.service.erb
  templates/pulpcore-content.service.erb
  templates/pulpcore-resource-manager.service.erb
  templates/pulpcore-worker@.service.erb
Labels: Bug, Needs testing

#115 Fixes #30423 - Change the application layout
  README.md
  manifests/apache.pp
  manifests/config.pp
  manifests/init.pp
  manifests/static.pp
  spec/classes/pulpcore_spec.rb
  templates/settings.py.erb
Labels: Backwards incompatible, Needs testing

#130 Fixes #31018 - Force UTF-8 database encoding
  manifests/database.pp
Labels: Needs testing

#131 Release 1.1.1
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing

#128 Expand README with more about the support policy.
  README.md
Labels: Needs testing

#134 Release 1.2.1
  CHANGELOG.md
  metadata.json
Labels: Needs testing

#124 Switch to using a Unix socket bind for API and Content services
  manifests/apache.pp
  manifests/config.pp
  manifests/init.pp
  manifests/service.pp
  spec/classes/pulpcore_spec.rb
  templates/pulpcore-api.service.erb
  templates/pulpcore-api.socket.erb
  templates/pulpcore-content.service.erb
  templates/pulpcore-content.socket.erb
Labels: Backwards incompatible, Needs testing

#135 Describe the service setup in README
  README.md
Labels: Needs testing

#140 Gh actions
  .github/workflows/acceptance.yml
  .github/workflows/cron.yml
  .github/workflows/unit.yml
  .travis.yml
Labels: Needs testing, skip-changelog

#139 Release 2.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog
