Repository theforeman/puppet-pulpcore, pull requests merged in 2021-05, with the labels that each got.

#186 Refs #32383: Configurable client certificate authentication to Pulp
  manifests/apache.pp
  manifests/init.pp
  spec/classes/pulpcore_spec.rb
Labels: Enhancement, Needs testing

#187 Allow Puppet 7 compatible versions of mods
  metadata.json
Labels: Needs testing, Not yet reviewed

#189 Bump version to 3.4.0
  metadata.json
Labels: Needs testing

#192 Pin camptocamp/systemd to 2.12.0 in testing
  .fixtures.yml
Labels: Needs testing

#193 Fixes #32622: Include StdEnvVars, ExportCertData SSL options in Apache
  manifests/apache.pp
Labels: Bug, Needs testing

#194 Release 2.2.3
  CHANGELOG.md
  metadata.json
Labels: Needs testing

#188 Release 3.4.0
  CHANGELOG.md
  HISTORY.md
Labels: Needs testing, skip-changelog

#195 Switch to voxpupuli-acceptance-1.0
  Gemfile
  spec/acceptance/basic_spec.rb
  spec/acceptance/hieradata/common.yaml
  spec/acceptance/hieradata/os/RedHat/7.yaml
  spec/acceptance/plugins_spec.rb
  spec/acceptance/use_pulp2_content_route_spec.rb
  spec/spec_helper_acceptance.rb
Labels: Needs testing

#196 Allow puppet/redis 7.x
  metadata.json
Labels: Needs testing

#199 Introduce a private socket_service helper
  manifests/service.pp
  manifests/socket_service.pp
  spec/classes/pulpcore_spec.rb
Labels: Needs testing
