Repository theforeman/puppet-pulpcore, pull requests merged in 2021-01, with the labels that each got.

#160 Allow setting parameters on the API and Content Apache proxy
  manifests/apache.pp
  spec/classes/pulpcore_spec.rb
  templates/apache-fragment.epp
Labels: Needs testing

#161 Add proxy params to plugin Pulp 2 content routes
  manifests/plugin/deb.pp
  manifests/plugin/file.pp
  manifests/plugin/rpm.pp
  spec/classes/plugin_deb_spec.rb
  spec/classes/plugin_file_spec.rb
  spec/classes/plugin_rpm_spec.rb
Labels: Needs testing

#163 Refs #31670 - don't timeout DB migrations
  manifests/admin.pp
  manifests/database.pp
Labels: Needs testing

#165 Fixes #31694: systemd service type should be Type
  templates/pulpcore-api.service.erb
  templates/pulpcore-content.service.erb
Labels: Bug, Needs testing

#166 Fixes #31694: systemd service type should be Type
  templates/pulpcore-api.service.erb
  templates/pulpcore-content.service.erb
Labels: Needs testing, Not yet reviewed

#167 Release 2.2.2
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#164 Support Pulp 3.9, drop earlier versions
  .github/workflows/acceptance.yml
  README.md
  manifests/config.pp
  manifests/init.pp
  manifests/repo.pp
  spec/classes/pulpcore_spec.rb
  templates/settings.py.erb
Labels: Backwards incompatible, Needs testing

#169 Include pulpcore in pulpcore::apache
  manifests/apache.pp
Labels: Bug, Needs testing

#168 Release 3.0.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing
