Repository theforeman/puppet-pulpcore, pull requests merged in 2021-04, with the labels that each got.

#181 Fixes #32309 - pulpcore-manager fails from certain directories
  manifests/admin.pp
  spec/defines/admin_spec.rb
Labels: Bug, Needs testing

#182 Release 3.2.1
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#183 Add support for ALLOWED_CONTENT_CHECKSUMS
  manifests/init.pp
  spec/classes/pulpcore_spec.rb
  spec/type_aliases/checksumtypes_spec.rb
  templates/settings.py.erb
  types/checksumtypes.pp
Labels: Enhancement, Needs testing

#184 Fixes #31950 - support ansible plugin
  manifests/plugin/ansible.pp
  spec/acceptance/plugins_spec.rb
  spec/classes/plugin_ansible_spec.rb
  spec/setup_acceptance_node.pp
Labels: Needs testing

#185 Release 3.3.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog
