Repository theforeman/puppet-pulpcore, pull requests merged in 2021-07, with the labels that each got.

#208 Support 3.14, drop 3.13
  .github/workflows/ci.yml
  README.md
  manifests/repo.pp
Labels: Needs testing

#204 Refs #32910: Add ability to enable content caching
  manifests/init.pp
  spec/acceptance/basic_spec.rb
  spec/classes/pulpcore_spec.rb
  templates/settings.py.erb
Labels: Enhancement, Needs testing

#203 Fixes #32891 - Add feature to enable new tasking system and enable it by default
  manifests/init.pp
  manifests/service.pp
  spec/acceptance/basic_spec.rb
  spec/acceptance/disable_new_tasking_system_spec.rb
  spec/acceptance/enable_new_tasking_system_spec.rb
  spec/acceptance/plugins_spec.rb
  spec/acceptance/use_pulp2_content_route_spec.rb
  spec/classes/pulpcore_spec.rb
  templates/settings.py.erb
Labels: Needs testing

#211 Bump version to 4.0.0
  metadata.json
Labels: Needs testing, skip-changelog

#207 Refs #32917 - Don't deploy or configure Redis with new tasking system
  manifests/database.pp
  manifests/init.pp
  spec/acceptance/basic_spec.rb
  spec/classes/pulpcore_spec.rb
  templates/settings.py.erb
Labels: Needs testing

#212 Fixes #32968: Add ability to modify log level
  manifests/init.pp
  spec/classes/pulpcore_spec.rb
  templates/settings.py.erb
Labels: Enhancement, Needs testing

#213 Release 4.0.0
  CHANGELOG.md
Labels: Needs testing, skip-changelog

#217 Revert "Refs #32917 - Don't deploy or configure Redis with new taskin…
  manifests/database.pp
  manifests/init.pp
  spec/acceptance/basic_spec.rb
  spec/classes/pulpcore_spec.rb
  templates/settings.py.erb
Labels: Bug, Needs testing

#219 Release 4.0.1
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#221 Bump version to 5.0.0
  metadata.json
Labels: Needs testing, skip-changelog

#197 Drop Puppet 5 support
  metadata.json
Labels: Backwards incompatible, Needs testing

#216 Contain Redis within database
  manifests/database.pp
  spec/classes/pulpcore_spec.rb
Labels: Bug, Needs testing, Not yet reviewed

#218 Use REDIS_URL as a configuration option
  spec/classes/pulpcore_spec.rb
  templates/settings.py.erb
Labels: Enhancement, Needs testing

#222 Release 5.0.0
  CHANGELOG.md
Labels: Needs testing, skip-changelog
