Repository theforeman/puppet-pulpcore, pull requests merged in 2021-06, with the labels that each got.

#174 Support Puppet 7
  .github/workflows/ci.yml
  metadata.json
Labels: Enhancement, Needs testing

#200 Fixes #32766 - adds scheme and pulp content path to setting value
  manifests/plugin/ansible.pp
  spec/classes/plugin_ansible_spec.rb
Labels: Bug, Needs testing

#201 Support version 3.11
  .github/workflows/ci.yml
  README.md
  manifests/repo.pp
Labels: Needs testing, Not yet reviewed

#202 Support Pulp 3.13, drop earlier versions
  .github/workflows/ci.yml
  README.md
  manifests/repo.pp
  templates/pulpcore-resource-manager.service.erb
  templates/pulpcore-worker@.service.erb
Labels: Backwards incompatible, Needs testing, Not yet reviewed
