Repository theforeman/puppet-pulpcore, pull requests merged in 2021-03, with the labels that each got.

#173 Update Github Actions workflow
  .github/workflows/acceptance.yml
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  .github/workflows/unit.yml
  .sync.yml
  Gemfile
Labels: Modulesync, Needs testing, Not yet reviewed

#177 Pin camptocamp/systemd to 2.12.0 in testing
  .fixtures.yml
Labels: Needs testing

#178 Fixes #32112 - Configure api service gunicorn worker timeout
  manifests/init.pp
  templates/pulpcore-api.service.erb
Labels: Enhancement, Needs testing

#175 Pulpcore logging format to include correlation id.
  templates/pulpcore-api.service.erb
Labels: Needs testing

#179 Refs #32112 - Match upstream pulp default api service worker timeout
  manifests/init.pp
  templates/pulpcore-content.service.erb
Labels: Needs testing

#180 Release 3.2.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog
