Repository theforeman/puppet-pulpcore, pull requests merged in 2022-11, with the labels that each got.

#270 Release 7.0.1
  CHANGELOG.md
  metadata.json
Labels: skip-changelog

#271 Remove unused CONTENT_HOST setting
  templates/settings.py.erb
Labels: Enhancement

#269 Expose Apache server aliases as a parameter
  manifests/apache.pp
  manifests/init.pp
  spec/classes/pulpcore_spec.rb
Labels: Enhancement

#273 Fix broken links in `README.md`
  README.md
Labels: documentation
