Repository theforeman/puppet-pulpcore, pull requests merged in 2022-01, with the labels that each got.

#209 Refactor pulpcore worker_count tests and add additional tests
  spec/acceptance/basic_spec.rb
  spec/acceptance/worker_count_spec.rb
  spec/classes/pulpcore_spec.rb
Labels: Needs testing, skip-changelog

#242 Fixes #34298 - support KEEP_CHANGELOG_LIMIT option
  manifests/plugin/rpm.pp
  spec/classes/plugin_rpm_spec.rb
Labels: Enhancement, Needs testing

#243 Release 5.2.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed, skip-changelog
