Repository theforeman/puppet-pulpcore, pull requests merged in 2023-05, with the labels that each got.

#280 Mark compatible with puppetlabs/postgresql 9.x & puppetlabs/apache 10.x & puppetlabs/concat 8.x
  metadata.json
Labels: Enhancement, Not yet reviewed

#281 Refs #36345 - Raise minimum Puppet version to 7.0.0
  metadata.json
Labels: Backwards incompatible

#284 Release 8.0.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog

#287 use `--workers` instead of `-w` when configuring gunicorn workers
  spec/classes/pulpcore_spec.rb
  templates/pulpcore-api.service.erb
  templates/pulpcore-content.service.erb
Labels: Enhancement

#288 Fixes #36437 - preload pulpcore API and content code
  templates/pulpcore-api.service.erb
  templates/pulpcore-content.service.erb
Labels: Enhancement

#289 Fixes #36438 - configure API request limit to avoid memory leaks
  manifests/init.pp
  spec/classes/pulpcore_spec.rb
  templates/pulpcore-api.service.erb
Labels: Enhancement

#290 Release 8.1.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog
