Repository theforeman/puppet-pulpcore, pull requests merged in 2023-11, with the labels that each got.

#311 Remove leftover from testing Pulpcore < 3.20
  spec/support/acceptance/examples.rb
Labels: skip-changelog

#297 Add Puppet 8 support
  metadata.json
Labels: Enhancement

#313 Mark compatible with puppet/systemd 6.x
  metadata.json
Labels: Enhancement

#314 Mark compatible with puppet-extlib 7.x
  metadata.json
Labels: Enhancement, Not yet reviewed

#316 Mark compatible with puppetlabs/postgresql 10.x
  metadata.json
Labels: Enhancement, Not yet reviewed

#317 Release 8.6.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog

#315 Fixes #36902 - Support Pulpcore 3.39, drop older versions
  .github/workflows/ci.yml
  .sync.yml
  README.md
  manifests/repo.pp
  spec/classes/repo_spec.rb
  templates/pulpcore-api.service.erb
  templates/pulpcore-content.service.erb
Labels: Backwards incompatible

#324 Release 9.0.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog
