Repository theforeman/puppet-pulpcore, pull requests merged in 2024-08, with the labels that each got.

#346 Add ability to configure auth backends and classes
  manifests/init.pp
  spec/acceptance/settings_spec.rb
  templates/settings.py.erb
Labels: Enhancement

#349 fix spec syntax of settings_spec.rb
  spec/acceptance/settings_spec.rb
Labels: Not yet reviewed, skip-changelog

#350 Release 10.2.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog

#351 Always run pulpcore-manager migrate
  manifests/database.pp
  spec/acceptance/hieradata/common.yaml
Labels: Bug

#352 explicitly support Pulpcore 3.49
  .github/workflows/ci.yml
  .sync.yml
  README.md
Labels: Enhancement

#353 Release 10.3.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog
