Repository theforeman/puppet-pulpcore, pull requests merged in 2024-09, with the labels that each got.

#354 Reuse headers from pulpcore::apache class
  manifests/plugin/container.pp
Labels: Enhancement

#357 Don't use underscores in HTTP headers
  manifests/apache.pp
  manifests/plugin/container.pp
  spec/classes/plugin_container_spec.rb
  spec/classes/pulpcore_spec.rb
  spec/support/acceptance/examples.rb
Labels: Bug

#358 Release 10.4.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog
