Repository theforeman/puppet-pulpcore, pull requests merged in 2024-02, with the labels that each got.

#325 Drop pulpcore::plugin::migration
  manifests/plugin/migration.pp
  spec/classes/plugin_migration_spec.rb
  templates/migration-settings.py.erb
Labels: Bug

#329 Ensure glibc-langpack-en is always installed
  manifests/database.pp
  spec/setup_acceptance_node.pp
Labels: Bug

#330 Mark compatible with puppet/redis 10.x
  metadata.json
Labels: Enhancement

#328 Release 10.0.0
  CHANGELOG.md
  metadata.json
Labels: Not yet reviewed, skip-changelog
